ingress:
  enabled: true
  tlsSecretName: app-tls

database:
  operator: false
  deletionProtected: true

resourcePrefix: ""

jobs:
  migration:
    enabled: true
    args: ["./docker/scripts/prepare-laravel && php artisan migrate --force"]

image: {}

phpDeployment:
  initContainer:
    enabled: true
    command: ["./docker/scripts/prepare-laravel"]
    args: []
    volumeMounts: []
    envFrom: []
  container:
    securityContext: {}
    volumeMounts: []
  volumes: []

redis:
  enabled: false

services:
  php-fpm:
    enabled: true
    port: 9000

hpa:
  php-fpm:
    enabled: false
    minReplicas: 2
    maxReplicas: 10

deployments:
  php-fpm:
    command: ['php-fpm']
    ports:
      - containerPort: 9000
    startupProbe:
      exec:
        command: ['./docker/scripts/php-fpm-healthcheck']
      initialDelaySeconds: 1
      failureThreshold: 30
      periodSeconds: 10
    resources:
      requests:
        cpu: 100m
      limits:
        cpu: 1000m

nginx:
  image: nginxinc/nginx-unprivileged
  tag: 1-alpine-slim
  volumeMounts: []
  initContainer:
    command: ['bash', '-c', './docker/nginx/prepare.sh']
    args: []
  volumes: []
  replicas: 1
  envFrom:
    - configMapRef:
        name: nginx-config
