{{- range $setKey, $setValues := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Values.resourcePrefix }}{{ $setKey }}
data:
  {{- range $key, $value := $setValues.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
{{- end }}
