{{- if.Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  annotations: {{- toYaml $.Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths: {{- toYaml $.Values.ingress.paths | nindent 10 }}
{{- end }}
{{- if.Values.ingress.tls }}
  tls:
    - secretName: app-tls
      hosts:
{{- range .Values.ingress.hosts }}
        - {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
