{{- range $key, $value := .Values.jobs }}
{{- if ne (hasKey $value "enabled") true | or (eq $value.enabled true) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Values.resourcePrefix }}{{ $key }}-{{ randAlphaNum 5 | lower }}
  labels:
    appVersion: {{ $.Values.appVersion | quote }}
spec:
  template:
    spec:
      containers:
        - name: {{ $key }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          command: ["/bin/bash", "-c"]
          args: {{ $value.args | toJson }}
          {{- $args := dict "envFrom" $.Values.phpDeployment.initContainer.envFrom "resourcePrefix" $.Values.resourcePrefix }}
          {{- include "chart.modifiedEnvFrom" $args | nindent 10 }}
      restartPolicy: Never
{{- if not (empty $.Values.image.registrySecretName) }}
      imagePullSecrets:
        - name: {{ $.Values.resourcePrefix }}{{ $.Values.image.registrySecretName }}
{{- end }}
  backoffLimit: 0
{{- end }}
{{- end }}
