apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourcePrefix }}nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: {{ .Values.resourcePrefix }}nginx
  template:
    metadata:
      name: nginx
      labels:
        app: {{ .Release.Name }}
        tier: {{ .Values.resourcePrefix }}nginx
        appVersion: {{ .Values.appVersion | quote }}
    spec:
      initContainers:
        - name: setup-nginx
{{- if.Values.image.pullPolicy }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: {{- toYaml $.Values.nginx.initContainer.command | nindent 12 }}
          args: {{- toYaml $.Values.nginx.initContainer.args | nindent 12 }}
          env:
            - name: PHP_FPM_NAME
              value:  "{{ .Values.resourcePrefix }}php-fpm"
          {{- $envFromArgs := dict "envFrom" .Values.nginx.envFrom "resourcePrefix" .Values.resourcePrefix }}
          {{- include "chart.modifiedEnvFrom" $envFromArgs | nindent 10 }}
          volumeMounts:
            - name: nginx-templates
              mountPath: /nginx/templates
            - name: nginx-snippets
              mountPath: /nginx/snippets
            - name: nginx-html
              mountPath: /nginx/html
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image }}:{{ .Values.nginx.tag }}"
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 101 # nginx uid
            runAsGroup: 101 # nginx gid
          volumeMounts:
            - name: nginx-templates
              mountPath: /etc/nginx/templates
              readOnly: true
            - name: nginx-snippets
              mountPath: /etc/nginx/snippets
              readOnly: true
            - name: nginx-html
              mountPath: /usr/share/www/public
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: nginx-tmp
              mountPath: /tmp
{{- if not (empty .Values.nginx.volumeMounts) }}
            {{- toYaml .Values.nginx.volumeMounts | nindent 12 }}
{{- end }}
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          ports:
            - containerPort: 8080
      volumes:
        - name: nginx-tmp
          emptyDir: {}
        - name: nginx-conf
          emptyDir: {}
        - name: nginx-snippets
          emptyDir: {}
        - name: nginx-templates
          emptyDir: {}
        - name: nginx-html
          emptyDir: {}
{{- if not (empty .Values.nginx.volumes) }}
        {{- $volumesArgs := dict "volumes" .Values.nginx.volumes "resourcePrefix" .Values.resourcePrefix }}
        {{- include "chart.modifiedVolumes" $volumesArgs | nindent 6 }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.resourcePrefix }}{{ .Values.image.registrySecretName }}
