apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.resourcePrefix }}nginx
spec:
{{- if .Values.nginx.nodePort }}
  type: NodePort
{{- end }}
  ports:
    - port: 80
      targetPort: 8080
{{- if .Values.nginx.nodePort }}
      nodePort: {{ .Values.nginx.nodePort }}
{{- end }}
      name: nginx
  selector:
    tier: {{ .Values.resourcePrefix }}nginx
