{{- range $setKey, $setValues := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.resourcePrefix }}{{ $setKey }}
{{- if $setValues.type }}
type: {{ $setValues.type  }}
{{- end }}
data:
  {{- range $key, $value := $setValues.data }}
  {{- if hasPrefix "HELM_SECRET:" $value }}
  {{ $key }}: {{ trimPrefix "HELM_SECRET:" $value | decryptAES $.Values.encryptionKey | b64enc }}
  {{- else }}
  {{-  printf "unecrypted secret: %s" $key | fail  }}
  {{- end }}
  {{- end }}
---
{{- end }}
