{{- range $key, $value := .Values.services }}
{{- if ne (hasKey $value "enabled") true | or (eq $value.enabled true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
spec:
  type: {{ $value.type | default "NodePort" }}
  ports:
    - port: {{ $value.port }}
      targetPort: {{ $value.port }}
  selector:
    tier: {{ $key }}
{{- end }}
{{- end }}
