{{- if.Values.storage }}
{{- range .Values.storage.volumes }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-{{ $.Release.Namespace }}-{{ .Values.resourcePrefix }}{{ .name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ $.Values.storage.hostPathBaseDirectory }}/{{ .name }}"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.resourcePrefix }}{{ .name }}
spec:
  volumeName: {{ $.Release.Name }}-{{ $.Release.Namespace }}-{{ .Values.resourcePrefix }}{{ .name }}
  accessModes:
    - {{ $.Values.storage.accessMode }}
  storageClassName: {{ $.Values.storage.className }}
  resources:
    requests:
      storage: {{ .size }}
---
{{- end }}
{{- end }}
