{{- if .Values.storage }}
{{- range .Values.storage.volumes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $.Values.resourcePrefix }}{{ .name }}
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteMany" }}
{{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
{{- end }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
